### ISSUE TITLE
Rename AdoptOpenJDK manifests to Adoptium

### ISSUE THREAD

**Issue by chawyehsu** [ScoopInstaller/Java#100]
Rename all `adoptX` to `adoptopenjdkX`. So users can search AdoptOpenJDK with keyword `adopt` or `openjdk` or `adoptopenjdk`.

e.g.
`adopt13-hotspot.json` ->`adoptopenjdk13-hotspot.json`

**Comment by se35710** [comment]
Not sure this is the right way to go. This would break most current installations of AdoptOpenJDK. An alternative would be to have `scoop search` search through `description` for matches in addition to manifest names.

Else, new manifests could use the longer naming, and leave the older unchanged.

**Comment by h404bi** [comment]
Renaming/migrating manifest is a so-hurt thing for end-users, I understand. And I think it's a thing about "To do or not to do", not about "right or wrong" currently.

A *hard-to-guess* manifest name can confuse end-users some time (https://github.com/ScoopInstaller/Main/issues/78#issuecomment-552106119).

(And the thing about migration: https://github.com/ScoopInstaller/Main/pull/324#issuecomment-521664880)

That's why I always want a *redirection*/*deprecation* feature, making manifest renaming/migrating painless:

**pwsh.json**
```json
{
    "deprecatedby": "main/powershell"
}
```

```
$ scoop update pwsh
This package is superseded by 'main/powershell', you should install that package from now on.
```

**Comment by viceice** [comment]
I would mention to also redirect `coretto8` to `coretto8-jdk`.

I've search today for a jdk version 8 and havn't found  either `coretto` or `adopt`

**Comment by se35710** [comment]
@viceice As outlined by the [wiki](https://github.com/lukesampson/scoop/wiki/Java#openjdk-8-with-oracle-hotspot-jvm), the preferred JDK 8 manifest to use is [adopt8-upstream.json](https://github.com/ScoopInstaller/Java/blob/master/bucket/adopt8-upstream.json).

But I somewhat agree with you, the initial naming should have included the -jdk suffix for JDK:s. Historically most of the manifests only were JDK:s, but then some of them started to build JRE:s because Oracle would not provide JRE builds anymore, and to those manifests we added the -jre suffix. The came the plethora of heap sizes, JVM:s, with/without JFX, etc, etc.

Maybe the time has come to add for visibility the -jdk suffix to all JDK:s too...

**Comment by se35710** [comment]
@chawyehsu Since AdoptOpenJDK is changing it's name to [Eclipse Adoptium](https://projects.eclipse.org/projects/adoptium), a name change will occur. I think we can hold off renaming the manifests until then, don't you agree?

**Comment by chawyehsu** [comment]
@se35710 reasonable

**Comment by imgx64** [comment]
[The transition from AdoptOpenJDK to Eclipse Adoptium is now complete][1].

Summary:
- HotSpot builds are now called [Temurin][2] and are provided by Eclipse Adoptium (It's a bit confusing, but Adoptium is the project, and Temurin is the product).
- OpenJ9 builds are now called [Semeru][3] and are provided by IBM.

My opinion is that the best way forward is creating new manifests for `temurin8-jdk`, `temurin11-jdk`, `temurin16-jdk`, `semeru8-jdk`, `semeru11-jdk`, and `semeru16-jdk`. As for the old `adopt*` manifests, there's nothing that can be done about them unless Scoop gains new "deprecation" feature, which is out of scope for this issue.

[1]: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
[2]: https://adoptium.net/releases.html
[3]: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/

**Comment by d3vel0per** [comment]
I think we can get rid of `-jdk` suffix since that is implicit and only add it for `-jre`. Since JDK 9 it was decided not to bundle JRE's anymore but a few have been done in the past till JDK 11 for benefit of the users.
Adoptium won't release any JRE binaries post 16 while other vendors are free to do so.

Additionally, I would suggest we drop all the non-LTS releases post the new ones come out as they would be a security burden in the long run.

**Comment by se35710** [comment]
> Additionally, I would suggest we drop all the non-LTS releases post the new ones come out as they would be a security burden in the long run.

The goal of this repository is to provide manifests for all available Java distributions, including nightly builds.
