### ISSUE TITLE
Add graalvm-jdk16

### ISSUE THREAD

**Issue by pigsflew** [ScoopInstaller/Java#303]
Right now, there's no package other than `nightly` for running against jdk16 even though it's available in current 21.x builds.

Additional thoughts:

 - Consider maybe stating the jdk version in use for `graalvm` and `graalvm-nightly` descriptions? The former is currently jdk11, but the latter is currently using *jdk17*. Additionally, there's no `graalvm-nightly-jdk17`.
 - The packages `graalvm-annual*` are misleading, as graalvm's "yearly releases" are just about vm major version number. So unless you're planning on keeping `graalvm-21` for the latest release in 2021, and `graalvm-20` for the latest release in 2020, and so on, it's not really worth anything.
 - The packages `graalvm-lts*` are misleading, since all of these package the "Community Edition", which offers *no LTS versions*. LTS is for the Oracle GraalVM Enterprise Edition, but the [EE releases](https://www.oracle.com/downloads/graalvm-downloads.html?selected_tab=2) use the [Oracle license and their license accept backend](https://docs.oracle.com/en/graalvm/enterprise/20/docs/overview/licensing-information/) like the Oracle JDK, which requires a login on their site.

**Comment by se35710** [comment]
> Consider maybe stating the jdk version in use for graalvm and graalvm-nightly descriptions? The former is currently jdk11, but the latter is currently using jdk17. Additionally, there's no graalvm-nightly-jdk17.

Yes, `graalvm-nightly-jdk16` should be renamed to `graalvm-nightly-jdk17` and updated accordingly.

> The packages graalvm-annual* are misleading, as graalvm's "yearly releases" are just about vm major version number. So unless you're planning on keeping graalvm-21 for the latest release in 2021, and graalvm-20 for the latest release in 2020, and so on, it's not really worth anything.

The annual term is from GraalVM version roadmap: https://www.graalvm.org/release-notes/version-roadmap/

> The packages graalvm-lts* are misleading, since all of these package the "Community Edition", which offers no LTS versions. LTS is for the Oracle GraalVM Enterprise Edition, but the EE releases use the Oracle license and their license accept backend like the Oracle JDK, which requires a login on their site.

There are at most three releases active at the same time. So the names are to reflect those three releases:

`graalvm` is always the latest version available
`-annual` is the release before the latest available
`-lts` is the release before annual, if it is available, otherwise it is the same as annual

For example:

After the April 20th release the versions would match the manifest names like this:

`graalvm`: 21.1.0
`graalvm-annual`: 20.3.2
`graalvm-lts`: 19.3.6

After the July 20th release the versions would look like this:

`graalvm`: 21.2.0
`graalvm-annual`: 20.3.3
`graalvm-lts`: 20.3.3

And then in January 2022:

`graalvm`: 22.0.0
`graalvm-annual`: 21.3.1
`graalvm-lts`: 20.3.5

Does that make sense? I am unsure on how to keep all releases downloadable at the same time as keeping current with all the different JDK variants.
