### ISSUE TITLE
Microsoft JDK extract_dir issues

### ISSUE THREAD

**Issue by se35710** [ScoopInstaller/Java#390]
Currently Microsoft JDK's `extract_dir` contains a build number not available at the download page at https://docs.microsoft.com/java/openjdk/download

Manual updates after each autoupdate is necessary with the current manifests. For a work around, maybe reuse the temurin nightly approach:
```JSON
    "extract_to": "tmp",
    "installer": {
        "script": [
            "(Get-ChildItem -Directory \"$dir\\tmp\").FullName | % { Move-Item \"$_\\*\" \"$dir\" }",
            "Remove-Item -Recurse \"$dir\\tmp\""
        ]
    }
```

**Comment by CrendKing** [comment]
The current manifest relies on the checkver regex to extract the build number from URL, which is not available. An example is v17.0.4 (https://aka.ms/download-jdk/microsoft-jdk-17.0.4-windows-x64.zip), which has a build number "8".

Since there seems to be only a directory anyways, I think we should just extract recursively, as OP suggested.
